import os

def generate_markdown_report(name, summary, usecases, datasets, solutions, save_path="reports"):
    # Create reports directory if it doesn't exist
    os.makedirs(save_path, exist_ok=True)

    # Sanitize file name
    file_name = f"{name.lower().replace(' ', '_')}_report.md"
    file_path = os.path.join(save_path, file_name)

    with open(file_path, "w", encoding="utf-8") as f:
        # Header
        f.write(f"# 📊 AI Market Research Report: **{name}**\n\n")
        f.write("---\n\n")

        # Industry Summary
        f.write("## 🧠 Industry Summary\n")
        f.write(f"{summary.strip()}\n\n")

        # Use Cases
        f.write("## 🚀 Proposed GenAI / ML Use Cases\n")
        for i, uc in enumerate(usecases, 1):
            f.write(f"### {i}. {uc.strip()}\n\n")

        # Datasets
        f.write("## 📚 Relevant Hugging Face Datasets\n")
        for keyword, link in datasets.items():
            f.write(f"- **{keyword}** → [{link}]({link})\n")
        f.write("\n")

        # Suggested GenAI Tools
        f.write("## 🧩 Suggested GenAI Tools / Architectures\n")
        if isinstance(solutions, list):
            for sol in solutions:
                f.write(f"- {sol.strip()}\n")
        else:
            f.write(f"{solutions.strip()}\n\n")


        f.write("---\n")
        f.write("_Report generated by your Multi-Agent GenAI Research Assistant._\n")

    return file_path
